### ISSUE TITLE
Compatibility with Python 3.9

### ISSUE THREAD

**Issue by amotl** [crate/crate-docs#47]
Hi there.

This is just a quick note. When running `make html` within `docker run -it --rm python:3.9.0 bash`, it errors out with
```
Installing collected packages: urllib3, pytz, pyparsing, MarkupSafe, idna, chardet, certifi, tornado, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, snowballstemmer, six, setuptools, requests, Pygments, packaging, Jinja2, imagesize, docutils, babel, alabaster, sphinx, livereload, sphinx-autobuild
    Running setup.py install for MarkupSafe ... done
  Attempting uninstall: setuptools
    Found existing installation: setuptools 49.2.1
    Uninstalling setuptools-49.2.1:
      Successfully uninstalled setuptools-49.2.1
    Running setup.py install for livereload ... error
    ERROR: Command errored out with exit status 1:
     command: /home/crate-docs/docs/.crate-docs/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jrn94hws/livereload_30ab7443dd23497e995991957799188a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jrn94hws/livereload_30ab7443dd23497e995991957799188a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9bgqgv7d/install-record.txt --single-version-externally-managed --compile --install-headers /home/crate-docs/docs/.crate-docs/.venv/include/site/python3.9/livereload
         cwd: /tmp/pip-install-jrn94hws/livereload_30ab7443dd23497e995991957799188a/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/crate-docs/docs/.crate-docs/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/home/crate-docs/docs/.crate-docs/.venv/lib/python3.9/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools.depends import Require
      File "/home/crate-docs/docs/.crate-docs/.venv/lib/python3.9/site-packages/setuptools/depends.py", line 7, in <module>
        from .py33compat import Bytecode
      File "/home/crate-docs/docs/.crate-docs/.venv/lib/python3.9/site-packages/setuptools/py33compat.py", line 55, in <module>
        unescape = getattr(html, 'unescape', html_parser.HTMLParser().unescape)
    AttributeError: 'HTMLParser' object has no attribute 'unescape'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/crate-docs/docs/.crate-docs/.venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jrn94hws/livereload_30ab7443dd23497e995991957799188a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jrn94hws/livereload_30ab7443dd23497e995991957799188a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9bgqgv7d/install-record.txt --single-version-externally-managed --compile --install-headers /home/crate-docs/docs/.crate-docs/.venv/include/site/python3.9/livereload Check the logs for full command output.
make[1]: *** [.crate-docs/src/rules.mk:110: .crate-docs/.venv/bin/sphinx-build] Error 1
make[1]: Leaving directory '/home/crate-docs/docs'
make: *** [Makefile:69: html] Error 2
```

With kind regards,
Andreas.

**Comment by amotl** [comment]
`HTMLParser.unescape` is deprecated since Python 3.4. However, old versions of `setuptools` are still using it, see https://github.com/pypa/setuptools/pull/1788.

According to https://github.com/pypa/setuptools/commit/53b8db359378f436bfd88f90a90aaf01b650d3a6, `setuptools>=41.1.0` should be fine.
